---
# tasks file for frontend
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  tags:
    - initial
    - packages

- name: Start and Enable Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
  tags:
    - initial

- name: Copy nginx configuration file
  ansible.builtin.copy:
    src: ../files/hello.conf
    dest: /etc/nginx/hello.conf
  notify: restart nginx service
  tags:
    - configure

- name: Copy index.html file
  ansible.builtin.copy:
    src: ../files/index.html
    dest: /var/www/frontend/index.html
  notify: restart nginx service
  tags:
    - configure
