---
# tasks file for frontend
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  tags:
    - initial
    - packages

- name: Start and Enable Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
  tags:
    - initial

- name: Copy nginx configuration file
  template:
    src: ../templates/hello.conf.j2
    dest: /etc/nginx/sites-available/hello.conf
  tags:
    - configure

- name: Update the symbolic link of default nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/hello.conf
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx service
  tags:
    - configure

- name: Create /var/www/frontend directory
  ansible.builtin.file:
    path: /var/www/frontend
    state: directory
    mode: "0755"
    owner: root
    group: www-data
  tags:
    - configure

- name: Copy index.html file
  ansible.builtin.copy:
    src: ../files/index.html
    dest: /var/www/frontend/index.html
  notify: restart nginx service
  tags:
    - configure
