---
# tasks file for backend
- name: Install required packages (curl, unzip, etc...)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - debian-archive-keyring
    - debian-keyring
  tags:
    - packages
    - initial

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  # args:
  #   creates: /usr/bin/caddy
  tags:
    - packages
    - caddy

- name: Start and Enable Caddy
  ansible.builtin.systemd_service:
    name: caddy
    enabled: yes
    state: started
  tags:
    - service
    - caddy

- name: Copy Caddyfile service
  ansible.builtin.copy:
    src: ../files/Caddyfile
    dest: /etc/caddy/Caddyfile
  notify: restart caddy service
  tags:
    - service
    - caddy

- name: Create /var/log/hello-server directory
  ansible.builtin.file:
    path: /var/log/hello-server
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags:
    - configure
    - app

- name: Create /var/www/backend directory
  ansible.builtin.file:
    path: /var/www/backend
    state: directory
    mode: "0755"
    owner: root
    group: ubuntu
  tags:
    - configure
    - app

- name: Copy compiled binary
  ansible.builtin.copy:
    src: ../files/hello-server
    dest: /var/www/backend/hello-server
    mode: "0755"
    owner: root
    group: ubuntu
  tags:
    - binary
    - app

- name: Copy service file
  ansible.builtin.copy:
    src: ../files/hello-server.service
    dest: /etc/systemd/system/hello-server.service
  # notify: restart backend service
  tags:
    - service
    - app

- name: start and enable hello-server service
  ansible.builtin.systemd_service:
    name: hello-server
    enabled: yes
    state: started
  tags:
    - service
    - app
