---
- name: Initialize Frontend and Backend Servers
  hosts: all
  become: true
  tasks:
    - name: Install required packages (curl, unzip, etc...)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - unzip
        - acl

    - name: Create tmp dir for ansible
      ansible.builtin.file:
        path: ~/.ansible/tmp
        state: directory
        mode: "1777"
        owner: root
        group: root

- name: Configure Frontend Servers with nginx
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: Configure Backend Servers with caddy and hello-server service
  hosts: backend
  become: true
  tags: backend
  roles:
    - backend
